### ISSUE TITLE
zip ruby support required

### ISSUE THREAD

**Issue by aaime** [GeoWebCache/gwc-release#1]
The script won't start unless the zip package is also installed. On my machine:

```
sudo gem2.0 install zip
```

**Comment by aaime** [comment]
Also consider the Zip::File vs Zip::ZipFile issue, maybe there is a way to have gem install the specific version that works?

**Comment by smithkm** [comment]
Added a Gemfile specifying the dependencies. 

All the dependencies can be installed and their versions checked using the following

```
gem install bundle
bundle install
```
