### ISSUE TITLE
Script requires the EDITOR variable to be set

### ISSUE THREAD

**Issue by aaime** [GeoWebCache/gwc-release#2]
Otherwise the update target won't work

**Comment by smithkm** [comment]
I added a more useful error message, and a way for the editor to be specified on the command line, or via a user_defaults.yml file (along with defaults for the other config options)

Example

```
upstream_remote: upstream
xsddoc_bin: /home/smithkm/bin/xsddoc-1.0/bin/xsddoc
dir: /home/smithkm/og-proj/geowebcache
sf_user: hai-etlik
web_user: smithkm
```
